name: tests

on: [push, pull_request]

jobs:

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip
      - name: Install Poetry
        uses: 20c/workflows/poetry@v1
        with:
          python-version: ${{ matrix.python-version }}
          install-options: -Eall
      - name: Run linters
        run: |
          poetry run isort src/
          poetry run black --check src/

  test:
    needs: linting
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
        python-version: [ "3.6", "3.7", "3.8", "3.9" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: 20c/workflows/poetry@v1
        with:
          python-version: ${{ matrix.python-version }}
          install-options: -Eall
      - name: Run tests
        run: |
          poetry run pytest -vv --cov-report=term-missing --cov=peeringdb --cov-report=xml tests/
          peotry run coverage report
      # upload coverage stats
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
